<a href="https://colab.research.google.com/github/eeelifsu/eeelifsu/blob/main/VB_YZ_Ders_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
import numpy as np
import pandas as pd

In [171]:
notlar = {"Gürhan": 58, "Ayşe": 60, "Leyla":78}

In [172]:
notlar

{'Gürhan': 58, 'Ayşe': 60, 'Leyla': 78}

In [173]:
pd.Series(notlar) #Series(tek boyutlu etiketli veri yapısı) dataframe temeli

Gürhan    58
Ayşe      60
Leyla     78
dtype: int64

In [174]:
numpy_array = np.array([20,30,40,50])

In [175]:
pd.Series(numpy_array)

0    20
1    30
2    40
3    50
dtype: int64

**Data Frame (DataFrame, satır ve sütunlardan oluşan 2 boyutlu tablo yapısıdır.)**

In [176]:
data = np.random.randint(10, size=(4,4))

In [177]:
data

array([[8, 4, 4, 7],
       [0, 1, 6, 0],
       [4, 9, 2, 7],
       [2, 4, 7, 3]])

In [178]:
data_frame = pd.DataFrame(data)

In [179]:
data_frame

   0  1  2  3
0  8  4  4  7
1  0  1  6  0
2  4  9  2  7
3  2  4  7  3

In [180]:
type(data_frame)

pandas.core.frame.DataFrame

In [181]:
data_frame

   0  1  2  3
0  8  4  4  7
1  0  1  6  0
2  4  9  2  7
3  2  4  7  3

In [182]:
new_df = pd.DataFrame(data, index= ["Gürhan","Ayşe","Elif", "Melike"], columns = ["Ders1","Ders2", "Ders3","Ders4"])

In [183]:
new_df

        Ders1  Ders2  Ders3  Ders4
Gürhan      8      4      4      7
Ayşe        0      1      6      0
Elif        4      9      2      7
Melike      2      4      7      3

In [184]:
new_df["Ders1"]

Gürhan    8
Ayşe      0
Elif      4
Melike    2
Name: Ders1, dtype: int64

In [185]:
new_df["Ders2"]

Gürhan    4
Ayşe      1
Elif      9
Melike    4
Name: Ders2, dtype: int64

In [186]:
new_df["Ders3"]

Gürhan    4
Ayşe      6
Elif      2
Melike    7
Name: Ders3, dtype: int64

In [187]:
#new_df["Gürhan"] #satır seçerken hata verir

In [188]:
new_df.loc["Elif"] # log kavramı bizim satırlarda gördüğümüz değere göre seçmemizi sağlar indexten bağımsız

Ders1    4
Ders2    9
Ders3    2
Ders4    7
Name: Elif, dtype: int64

In [189]:
new_df.iloc[0] # index numarasına göre getirir

Ders1    8
Ders2    4
Ders3    4
Ders4    7
Name: Gürhan, dtype: int64

In [190]:
new_df.iloc[3]

Ders1    2
Ders2    4
Ders3    7
Ders4    3
Name: Melike, dtype: int64

In [191]:
new_df.loc[["Ayşe","Elif"]]

      Ders1  Ders2  Ders3  Ders4
Ayşe      0      1      6      0
Elif      4      9      2      7

In [192]:
new_df.loc["Gürhan":"Elif"]

        Ders1  Ders2  Ders3  Ders4
Gürhan      8      4      4      7
Ayşe        0      1      6      0
Elif        4      9      2      7

In [193]:
new_df.iloc[0:2]

        Ders1  Ders2  Ders3  Ders4
Gürhan      8      4      4      7
Ayşe        0      1      6      0

In [194]:
new_df.iloc[0:3]

        Ders1  Ders2  Ders3  Ders4
Gürhan      8      4      4      7
Ayşe        0      1      6      0
Elif        4      9      2      7

In [195]:
new_df.iloc[0:3,1:3]

        Ders2  Ders3
Gürhan      4      4
Ayşe        1      6
Elif        9      2

In [196]:
new_df[["Ders5"]] = 8

In [197]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5
Gürhan      8      4      4      7      8
Ayşe        0      1      6      0      8
Elif        4      9      2      7      8
Melike      2      4      7      3      8

In [198]:
new_df["Ders5"] = [3,4,5,6]

In [199]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5
Gürhan      8      4      4      7      3
Ayşe        0      1      6      0      4
Elif        4      9      2      7      5
Melike      2      4      7      3      6

In [200]:
new_df["Ders6"] = [2,4,1,9]

In [201]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      8      4      4      7      3      2
Ayşe        0      1      6      0      4      4
Elif        4      9      2      7      5      1
Melike      2      4      7      3      6      9

In [202]:
new_df["Ders7"] = new_df["Ders3"] * 3

In [203]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6  Ders7
Gürhan      8      4      4      7      3      2     12
Ayşe        0      1      6      0      4      4     18
Elif        4      9      2      7      5      1      6
Melike      2      4      7      3      6      9     21

In [204]:
new_df.drop("Ders7", axis=1) #Sütun silme axis parametresi 1 verildi. Dütun bazlı işlem için

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      8      4      4      7      3      2
Ayşe        0      1      6      0      4      4
Elif        4      9      2      7      5      1
Melike      2      4      7      3      6      9

In [205]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6  Ders7
Gürhan      8      4      4      7      3      2     12
Ayşe        0      1      6      0      4      4     18
Elif        4      9      2      7      5      1      6
Melike      2      4      7      3      6      9     21

In [206]:
new_df_2 = new_df.drop("Ders7", axis=1)

In [207]:
new_df_2

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders6
Gürhan      8      4      4      7      3      2
Ayşe        0      1      6      0      4      4
Elif        4      9      2      7      5      1
Melike      2      4      7      3      6      9

In [208]:
new_df.drop("Ders6", axis=1, inplace=True)

In [209]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      4      4      7      3     12
Ayşe        0      1      6      0      4     18
Elif        4      9      2      7      5      6
Melike      2      4      7      3      6     21

In [210]:
new_df.loc["Mehmet"] = 15

In [211]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      4      4      7      3     12
Ayşe        0      1      6      0      4     18
Elif        4      9      2      7      5      6
Melike      2      4      7      3      6     21
Mehmet     15     15     15     15     15     15

In [212]:
new_df.loc["Ahmet"] = [3,5,7,8,4,2]

In [213]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      4      4      7      3     12
Ayşe        0      1      6      0      4     18
Elif        4      9      2      7      5      6
Melike      2      4      7      3      6     21
Mehmet     15     15     15     15     15     15
Ahmet       3      5      7      8      4      2

In [214]:
new_df.iloc[0, 0:1]

Ders1    8
Name: Gürhan, dtype: int64

In [215]:
new_df.loc["Ahmet","Ders1"] = 5

In [216]:
new_df

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      4      4      7      3     12
Ayşe        0      1      6      0      4     18
Elif        4      9      2      7      5      6
Melike      2      4      7      3      6     21
Mehmet     15     15     15     15     15     15
Ahmet       5      5      7      8      4      2

 **Boolean**

In [217]:
bool_frame =new_df > 5

In [218]:
bool_frame

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan   True  False  False   True  False   True
Ayşe    False  False   True  False  False   True
Elif    False   True  False   True  False   True
Melike  False  False   True  False   True   True
Mehmet   True   True   True   True   True   True
Ahmet   False  False   True   True  False  False

In [219]:
new_df[new_df >5]

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan    8.0    NaN    NaN    7.0    NaN   12.0
Ayşe      NaN    NaN    6.0    NaN    NaN   18.0
Elif      NaN    9.0    NaN    7.0    NaN    6.0
Melike    NaN    NaN    7.0    NaN    6.0   21.0
Mehmet   15.0   15.0   15.0   15.0   15.0   15.0
Ahmet     NaN    NaN    7.0    8.0    NaN    NaN

In [220]:
new_df[new_df["Ders1"]>5]

        Ders1  Ders2  Ders3  Ders4  Ders5  Ders7
Gürhan      8      4      4      7      3     12
Mehmet     15     15     15     15     15     15

.csv dosya okuma, gerçek dataları içeri alma

In [221]:
import pandas as pd

satis_df = pd.read_csv("/content/satislar.csv")

satis_df

       Urun    Kategori  Fiyat  Adet     Sehir Satis_Temsilcisi
0    Laptop  Bilgisayar  35000     2  Istanbul             Elif
1   Telefon     Telefon  25000     5    Ankara            Ahmet
2    Tablet      Tablet  18000     3     Izmir           Zeynep
3  Kulaklik    Aksesuar   2500    10   Kayseri           Mehmet
4   Monitor     Monitor   9000     4  Istanbul             Elif
5    Klavye    Aksesuar   1800     8    Ankara             Ayse
6     Mouse    Aksesuar    900    15     Bursa            Ahmet
7    Webcam    Aksesuar   3200     6   Kayseri           Zeynep
8    Laptop  Bilgisayar  42000     1     Izmir           Mehmet
9   Telefon     Telefon  28000     3  Istanbul             Elif

In [222]:
satis_df.head()

       Urun    Kategori  Fiyat  Adet     Sehir Satis_Temsilcisi
0    Laptop  Bilgisayar  35000     2  Istanbul             Elif
1   Telefon     Telefon  25000     5    Ankara            Ahmet
2    Tablet      Tablet  18000     3     Izmir           Zeynep
3  Kulaklik    Aksesuar   2500    10   Kayseri           Mehmet
4   Monitor     Monitor   9000     4  Istanbul             Elif

In [223]:
satis_df.shape

(10, 6)

In [224]:
satis_df["Urun"]

0      Laptop
1     Telefon
2      Tablet
3    Kulaklik
4     Monitor
5      Klavye
6       Mouse
7      Webcam
8      Laptop
9     Telefon
Name: Urun, dtype: object

In [225]:
satis_df["Fiyat"]

0    35000
1    25000
2    18000
3     2500
4     9000
5     1800
6      900
7     3200
8    42000
9    28000
Name: Fiyat, dtype: int64

In [226]:
satis_df.loc[0]

Urun                    Laptop
Kategori            Bilgisayar
Fiyat                    35000
Adet                         2
Sehir                 Istanbul
Satis_Temsilcisi          Elif
Name: 0, dtype: object

In [227]:
satis_df.tail()

      Urun    Kategori  Fiyat  Adet     Sehir Satis_Temsilcisi
5   Klavye    Aksesuar   1800     8    Ankara             Ayse
6    Mouse    Aksesuar    900    15     Bursa            Ahmet
7   Webcam    Aksesuar   3200     6   Kayseri           Zeynep
8   Laptop  Bilgisayar  42000     1     Izmir           Mehmet
9  Telefon     Telefon  28000     3  Istanbul             Elif

In [228]:
satis_df.describe() #dataframe hakkında istatistiksel verileri veriyor.

              Fiyat       Adet
count     10.000000  10.000000
mean   16540.000000   5.700000
std    15230.904256   4.270051
min      900.000000   1.000000
25%     2675.000000   3.000000
50%    13500.000000   4.500000
75%    27250.000000   7.500000
max    42000.000000  15.000000

In [229]:
satis_df.columns

Index(['Urun', 'Kategori', 'Fiyat', 'Adet', 'Sehir', 'Satis_Temsilcisi'], dtype='object')

In [230]:
satis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Urun              10 non-null     object
 1   Kategori          10 non-null     object
 2   Fiyat             10 non-null     int64
 3   Adet              10 non-null     int64
 4   Sehir             10 non-null     object
 5   Satis_Temsilcisi  10 non-null     object
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [231]:
satis_df.isna()

    Urun  Kategori  Fiyat   Adet  Sehir  Satis_Temsilcisi
0  False     False  False  False  False             False
1  False     False  False  False  False             False
2  False     False  False  False  False             False
3  False     False  False  False  False             False
4  False     False  False  False  False             False
5  False     False  False  False  False             False
6  False     False  False  False  False             False
7  False     False  False  False  False             False
8  False     False  False  False  False             False
9  False     False  False  False  False             False

In [232]:
notlar_df = pd.read_csv("/content/notlar.csv")

In [233]:

notlar_df

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0          101           18.0          1.0    81.0    84.0    83.0   75.0
1          102            9.0          7.0    59.0    52.0    60.0    NaN
2          103            NaN          7.0    77.0    62.0    74.0   69.0
3          104            5.0         12.0    63.0    51.0    59.0   40.0
4          105           10.0          7.0     NaN    63.0    70.0   74.0
5          106            6.0          NaN    55.0    51.0    51.0   63.0
6          107            6.0         99.0    61.0    57.0    50.0   48.0
7          108           13.0          7.0    77.0     NaN    71.0   73.0
8          109           13.0          7.0    73.0    73.0    70.0    NaN
9          110            NaN          9.0    65.0    55.0    54.0   65.0
10         111           23.0          0.0   100.0   100.0   100.0  100.0
11         112            3.0         10.0    52.0    57.0     NaN   61.0
12         113            7.0          7.0    62.0    49.0    61.0   63.0
13         114           15.0          2.0    87.0     NaN    93.0   78.0
14         115           11.0         11.0     NaN     NaN     NaN   47.0
15         116           19.0          3.0    78.0    80.0    79.0   87.0
16         117           20.0          0.0    91.0    88.0    88.0   75.0
17         118            9.0          NaN    55.0    62.0    56.0   45.0
18         119            7.0          9.0    65.0    54.0    57.0   71.0
19         120           10.0          7.0    66.0    72.0    75.0    NaN
20         121           10.0          6.0    54.0   950.0    54.0   65.0
21         122            NaN          1.0    83.0    83.0    91.0   90.0
22         123           17.0          2.0    88.0    87.0    82.0   79.0
23         124           15.0          4.0    86.0    78.0    81.0   77.0
24         125            7.0          9.0    62.0    55.0     NaN   57.0
25         126           14.0          4.0    66.0    72.0    67.0    NaN
26         127           17.0          4.0     NaN    69.0    76.0   64.0
27         128           12.0          9.0    63.0    70.0    65.0   70.0
28         129           12.0          7.0    72.0     NaN    61.0   63.0
29         130           12.0          5.0    75.0    64.0    76.0   63.0
30         104            5.0         12.0    63.0    51.0    59.0   40.0
31         113            7.0          7.0    62.0    49.0    61.0   63.0

In [234]:
notlar_df.head() # data frame'in ilk 5 verisini getirir.

   ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0         101           18.0          1.0    81.0    84.0    83.0   75.0
1         102            9.0          7.0    59.0    52.0    60.0    NaN
2         103            NaN          7.0    77.0    62.0    74.0   69.0
3         104            5.0         12.0    63.0    51.0    59.0   40.0
4         105           10.0          7.0     NaN    63.0    70.0   74.0

In [235]:
notlar_df.tail() # data frame'in son 5 verisini getirir.

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
27         128           12.0          9.0    63.0    70.0    65.0   70.0
28         129           12.0          7.0    72.0     NaN    61.0   63.0
29         130           12.0          5.0    75.0    64.0    76.0   63.0
30         104            5.0         12.0    63.0    51.0    59.0   40.0
31         113            7.0          7.0    62.0    49.0    61.0   63.0

In [236]:
notlar_df.describe() # dataframe hakkında temel istatistiksel verileri veriyor.

,ogrenci_no,calisma_saati,devamsizlik,sinav1,sinav2,sinav3,proje
count,32.000000,29.000000,30.000000,29.000000,28.000000,29.000000,28.000000
mean,115.062500,11.448276,9.166667,70.379310,97.785714,69.793103,66.607143
std,8.761858,5.060958,17.302747,12.462555,167.596154,13.467897,14.345832
min,101.000000,3.000000,0.000000,52.000000,49.000000,50.000000,40.000000
25%,107.750000,7.000000,4.000000,62.000000,54.750000,59.000000,62.500000
50%,114.500000,11.000000,7.000000,66.000000,63.500000,70.000000,65.000000
75%,122.250000,15.000000,9.000000,78.000000,78.500000,79.000000,75.000000
max,130.000000,23.000000,99.000000,100.000000,950.000000,100.000000,100.000000

In [237]:

notlar_df.shape # satır ve sütun sayıları

(32, 7)

In [238]:

notlar_df.columns

Index(['ogrenci_no', 'calisma_saati', 'devamsizlik', 'sinav1', 'sinav2',
       'sinav3', 'proje'],
      dtype='object')

In [239]:
notlar_df.info()# Dataframe Sütunları ile ilgili genel bilgi.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ogrenci_no     32 non-null     int64
 1   calisma_saati  29 non-null     float64
 2   devamsizlik    30 non-null     float64
 3   sinav1         29 non-null     float64
 4   sinav2         28 non-null     float64
 5   sinav3         29 non-null     float64
 6   proje          28 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 1.9 KB

In [240]:
notlar_df.isna() # boş değerler ile ilgili boşta true

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0        False          False        False   False   False   False  False
1        False          False        False   False   False   False   True
2        False           True        False   False   False   False  False
3        False          False        False   False   False   False  False
4        False          False        False    True   False   False  False
5        False          False         True   False   False   False  False
6        False          False        False   False   False   False  False
7        False          False        False   False    True   False  False
8        False          False        False   False   False   False   True
9        False           True        False   False   False   False  False
10       False          False        False   False   False   False  False
11       False          False        False   False   False    True  False
12       False          False        False   False   False   False  False
13       False          False        False   False    True   False  False
14       False          False        False    True    True    True  False
15       False          False        False   False   False   False  False
16       False          False        False   False   False   False  False
17       False          False         True   False   False   False  False
18       False          False        False   False   False   False  False
19       False          False        False   False   False   False   True
20       False          False        False   False   False   False  False
21       False           True        False   False   False   False  False
22       False          False        False   False   False   False  False
23       False          False        False   False   False   False  False
24       False          False        False   False   False    True  False
25       False          False        False   False   False   False   True
26       False          False        False    True   False   False  False
27       False          False        False   False   False   False  False
28       False          False        False   False    True   False  False
29       False          False        False   False   False   False  False
30       False          False        False   False   False   False  False
31       False          False        False   False   False   False  False

In [241]:
notlar_df["sinav1"].isna()  # boş değerler ile ilgili sütun seçtik. boşsa true

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
31    False
Name: sinav1, dtype: bool

In [242]:
notlar_df.fillna(10)

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0          101           18.0          1.0    81.0    84.0    83.0   75.0
1          102            9.0          7.0    59.0    52.0    60.0   10.0
2          103           10.0          7.0    77.0    62.0    74.0   69.0
3          104            5.0         12.0    63.0    51.0    59.0   40.0
4          105           10.0          7.0    10.0    63.0    70.0   74.0
5          106            6.0         10.0    55.0    51.0    51.0   63.0
6          107            6.0         99.0    61.0    57.0    50.0   48.0
7          108           13.0          7.0    77.0    10.0    71.0   73.0
8          109           13.0          7.0    73.0    73.0    70.0   10.0
9          110           10.0          9.0    65.0    55.0    54.0   65.0
10         111           23.0          0.0   100.0   100.0   100.0  100.0
11         112            3.0         10.0    52.0    57.0    10.0   61.0
12         113            7.0          7.0    62.0    49.0    61.0   63.0
13         114           15.0          2.0    87.0    10.0    93.0   78.0
14         115           11.0         11.0    10.0    10.0    10.0   47.0
15         116           19.0          3.0    78.0    80.0    79.0   87.0
16         117           20.0          0.0    91.0    88.0    88.0   75.0
17         118            9.0         10.0    55.0    62.0    56.0   45.0
18         119            7.0          9.0    65.0    54.0    57.0   71.0
19         120           10.0          7.0    66.0    72.0    75.0   10.0
20         121           10.0          6.0    54.0   950.0    54.0   65.0
21         122           10.0          1.0    83.0    83.0    91.0   90.0
22         123           17.0          2.0    88.0    87.0    82.0   79.0
23         124           15.0          4.0    86.0    78.0    81.0   77.0
24         125            7.0          9.0    62.0    55.0    10.0   57.0
25         126           14.0          4.0    66.0    72.0    67.0   10.0
26         127           17.0          4.0    10.0    69.0    76.0   64.0
27         128           12.0          9.0    63.0    70.0    65.0   70.0
28         129           12.0          7.0    72.0    10.0    61.0   63.0
29         130           12.0          5.0    75.0    64.0    76.0   63.0
30         104            5.0         12.0    63.0    51.0    59.0   40.0
31         113            7.0          7.0    62.0    49.0    61.0   63.0

In [243]:
notlar_df

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0          101           18.0          1.0    81.0    84.0    83.0   75.0
1          102            9.0          7.0    59.0    52.0    60.0    NaN
2          103            NaN          7.0    77.0    62.0    74.0   69.0
3          104            5.0         12.0    63.0    51.0    59.0   40.0
4          105           10.0          7.0     NaN    63.0    70.0   74.0
5          106            6.0          NaN    55.0    51.0    51.0   63.0
6          107            6.0         99.0    61.0    57.0    50.0   48.0
7          108           13.0          7.0    77.0     NaN    71.0   73.0
8          109           13.0          7.0    73.0    73.0    70.0    NaN
9          110            NaN          9.0    65.0    55.0    54.0   65.0
10         111           23.0          0.0   100.0   100.0   100.0  100.0
11         112            3.0         10.0    52.0    57.0     NaN   61.0
12         113            7.0          7.0    62.0    49.0    61.0   63.0
13         114           15.0          2.0    87.0     NaN    93.0   78.0
14         115           11.0         11.0     NaN     NaN     NaN   47.0
15         116           19.0          3.0    78.0    80.0    79.0   87.0
16         117           20.0          0.0    91.0    88.0    88.0   75.0
17         118            9.0          NaN    55.0    62.0    56.0   45.0
18         119            7.0          9.0    65.0    54.0    57.0   71.0
19         120           10.0          7.0    66.0    72.0    75.0    NaN
20         121           10.0          6.0    54.0   950.0    54.0   65.0
21         122            NaN          1.0    83.0    83.0    91.0   90.0
22         123           17.0          2.0    88.0    87.0    82.0   79.0
23         124           15.0          4.0    86.0    78.0    81.0   77.0
24         125            7.0          9.0    62.0    55.0     NaN   57.0
25         126           14.0          4.0    66.0    72.0    67.0    NaN
26         127           17.0          4.0     NaN    69.0    76.0   64.0
27         128           12.0          9.0    63.0    70.0    65.0   70.0
28         129           12.0          7.0    72.0     NaN    61.0   63.0
29         130           12.0          5.0    75.0    64.0    76.0   63.0
30         104            5.0         12.0    63.0    51.0    59.0   40.0
31         113            7.0          7.0    62.0    49.0    61.0   63.0

In [244]:
notlar_df.fillna(notlar_df.mean())

,ogrenci_no,calisma_saati,devamsizlik,sinav1,sinav2,sinav3,proje
0,101,18.000000,1.000000,81.00000,84.000000,83.000000,75.000000
1,102,9.000000,7.000000,59.00000,52.000000,60.000000,66.607143
2,103,11.448276,7.000000,77.00000,62.000000,74.000000,69.000000
3,104,5.000000,12.000000,63.00000,51.000000,59.000000,40.000000
4,105,10.000000,7.000000,70.37931,63.000000,70.000000,74.000000
5,106,6.000000,9.166667,55.00000,51.000000,51.000000,63.000000
6,107,6.000000,99.000000,61.00000,57.000000,50.000000,48.000000
7,108,13.000000,7.000000,77.00000,97.785714,71.000000,73.000000
8,109,13.000000,7.000000,73.00000,73.000000,70.000000,66.607143
9,110,11.448276,9.000000,65.00000,55.000000,54.000000,65.000000
10,111,23.000000,0.000000,100.00000,100.000000,100.000000,100.000000
11,112,3.000000,10.000000,52.00000,57.000000,69.793103,61.000000
12,113,7.000000,7.000000,62.00000,49.000000,61.000000,63.000000
13,114,15.000000,2.000000,87.00000,97.785714,93.000000,78.000000
14,115,11.000000,11.000000,70.37931,97.785714,69.793103,47.000000
15,116,19.000000,3.000000,78.00000,80.000000,79.000000,87.000000
16,117,20.000000,0.000000,91.00000,88.000000,88.000000,75.000000
17,118,9.000000,9.166667,55.00000,62.000000,56.000000,45.000000
18,119,7.000000,9.000000,65.00000,54.000000,57.000000,71.000000
19,120,10.000000,7.000000,66.00000,72.000000,75.000000,66.607143
20,121,10.000000,6.000000,54.00000,950.000000,54.000000,65.000000
21,122,11.448276,1.000000,83.00000,83.000000,91.000000,90.000000
22,123,17.000000,2.000000,88.00000,87.000000,82.000000,79.000000
23,124,15.000000,4.000000,86.00000,78.000000,81.000000,77.000000
24,125,7.000000,9.000000,62.00000,55.000000,69.793103,57.000000
25,126,14.000000,4.000000,66.00000,72.000000,67.000000,66.607143
26,127,17.000000,4.000000,70.37931,69.000000,76.000000,64.000000
27,128,12.000000,9.000000,63.00000,70.000000,65.000000,70.000000
28,129,12.000000,7.000000,72.00000,97.785714,61.000000,63.000000
29,130,12.000000,5.000000,75.00000,64.000000,76.000000,63.000000
30,104,5.000000,12.000000,63.00000,51.000000,59.000000,40.000000
31,113,7.000000,7.000000,62.00000,49.000000,61.000000,63.000000

In [245]:
notlar_df.max()

ogrenci_no       130.0
calisma_saati     23.0
devamsizlik       99.0
sinav1           100.0
sinav2           950.0
sinav3           100.0
proje            100.0
dtype: float64

In [246]:
notlar_df

    ogrenci_no  calisma_saati  devamsizlik  sinav1  sinav2  sinav3  proje
0          101           18.0          1.0    81.0    84.0    83.0   75.0
1          102            9.0          7.0    59.0    52.0    60.0    NaN
2          103            NaN          7.0    77.0    62.0    74.0   69.0
3          104            5.0         12.0    63.0    51.0    59.0   40.0
4          105           10.0          7.0     NaN    63.0    70.0   74.0
5          106            6.0          NaN    55.0    51.0    51.0   63.0
6          107            6.0         99.0    61.0    57.0    50.0   48.0
7          108           13.0          7.0    77.0     NaN    71.0   73.0
8          109           13.0          7.0    73.0    73.0    70.0    NaN
9          110            NaN          9.0    65.0    55.0    54.0   65.0
10         111           23.0          0.0   100.0   100.0   100.0  100.0
11         112            3.0         10.0    52.0    57.0     NaN   61.0
12         113            7.0          7.0    62.0    49.0    61.0   63.0
13         114           15.0          2.0    87.0     NaN    93.0   78.0
14         115           11.0         11.0     NaN     NaN     NaN   47.0
15         116           19.0          3.0    78.0    80.0    79.0   87.0
16         117           20.0          0.0    91.0    88.0    88.0   75.0
17         118            9.0          NaN    55.0    62.0    56.0   45.0
18         119            7.0          9.0    65.0    54.0    57.0   71.0
19         120           10.0          7.0    66.0    72.0    75.0    NaN
20         121           10.0          6.0    54.0   950.0    54.0   65.0
21         122            NaN          1.0    83.0    83.0    91.0   90.0
22         123           17.0          2.0    88.0    87.0    82.0   79.0
23         124           15.0          4.0    86.0    78.0    81.0   77.0
24         125            7.0          9.0    62.0    55.0     NaN   57.0
25         126           14.0          4.0    66.0    72.0    67.0    NaN
26         127           17.0          4.0     NaN    69.0    76.0   64.0
27         128           12.0          9.0    63.0    70.0    65.0   70.0
28         129           12.0          7.0    72.0     NaN    61.0   63.0
29         130           12.0          5.0    75.0    64.0    76.0   63.0
30         104            5.0         12.0    63.0    51.0    59.0   40.0
31         113            7.0          7.0    62.0    49.0    61.0   63.0

In [247]:
notlar_df["sinav1"]

0      81.0
1      59.0
2      77.0
3      63.0
4       NaN
5      55.0
6      61.0
7      77.0
8      73.0
9      65.0
10    100.0
11     52.0
12     62.0
13     87.0
14      NaN
15     78.0
16     91.0
17     55.0
18     65.0
19     66.0
20     54.0
21     83.0
22     88.0
23     86.0
24     62.0
25     66.0
26      NaN
27     63.0
28     72.0
29     75.0
30     63.0
31     62.0
Name: sinav1, dtype: float64

In [258]:
notlar_df["sinav1"].mean

<bound method Series.mean of 0                                                  81.0
1                                                  59.0
2                                                  77.0
3                                                  63.0
4     <bound method Series.mean of 0      81.0\n1   ...
5                                                  55.0
6                                                  61.0
7                                                  77.0
8                                                  73.0
9                                                  65.0
10                                                100.0
11                                                 52.0
12                                                 62.0
13                                                 87.0
14    <bound method Series.mean of 0      81.0\n1   ...
15                                                 78.0
16                                                 91.0
17                                                 55.0
18                                                 65.0
19                                                 66.0
20                                                 54.0
21                                                 83.0
22                                                 88.0
23                                                 86.0
24                                                 62.0
25                                                 66.0
26    <bound method Series.mean of 0      81.0\n1   ...
27                                                 63.0
28                                                 72.0
29                                                 75.0
30                                                 63.0
31                                                 62.0
Name: sinav1, dtype: object>

In [263]:
notlar_df["sinav1"] = notlar_df["sinav1"].fillna(notlar_df["sinav1"].mean())

TypeError: unsupported operand type(s) for +: 'float' and 'method'

In [260]:
notlar_df

,ogrenci_no,calisma_saati,devamsizlik,sinav1,sinav2,sinav3,proje
0,101,18.0,1.0,81.0,84.0,83.0,75.0
1,102,9.0,7.0,59.0,52.0,60.0,NaN
2,103,NaN,7.0,77.0,62.0,74.0,69.0
3,104,5.0,12.0,63.0,51.0,59.0,40.0
4,105,10.0,7.0,<bound method Series.mean of 0 81.0\n1 ...,63.0,70.0,74.0
5,106,6.0,NaN,55.0,51.0,51.0,63.0
6,107,6.0,99.0,61.0,57.0,50.0,48.0
7,108,13.0,7.0,77.0,NaN,71.0,73.0
8,109,13.0,7.0,73.0,73.0,70.0,NaN
9,110,NaN,9.0,65.0,55.0,54.0,65.0
10,111,23.0,0.0,100.0,100.0,100.0,100.0
11,112,3.0,10.0,52.0,57.0,NaN,61.0
12,113,7.0,7.0,62.0,49.0,61.0,63.0
13,114,15.0,2.0,87.0,NaN,93.0,78.0
14,115,11.0,11.0,<bound method Series.mean of 0 81.0\n1 ...,NaN,NaN,47.0
15,116,19.0,3.0,78.0,80.0,79.0,87.0
16,117,20.0,0.0,91.0,88.0,88.0,75.0
17,118,9.0,NaN,55.0,62.0,56.0,45.0
18,119,7.0,9.0,65.0,54.0,57.0,71.0
19,120,10.0,7.0,66.0,72.0,75.0,NaN
20,121,10.0,6.0,54.0,950.0,54.0,65.0
21,122,NaN,1.0,83.0,83.0,91.0,90.0
22,123,17.0,2.0,88.0,87.0,82.0,79.0
23,124,15.0,4.0,86.0,78.0,81.0,77.0
24,125,7.0,9.0,62.0,55.0,NaN,57.0
25,126,14.0,4.0,66.0,72.0,67.0,NaN
26,127,17.0,4.0,<bound method Series.mean of 0 81.0\n1 ...,69.0,76.0,64.0
27,128,12.0,9.0,63.0,70.0,65.0,70.0
28,129,12.0,7.0,72.0,NaN,61.0,63.0
29,130,12.0,5.0,75.0,64.0,76.0,63.0
30,104,5.0,12.0,63.0,51.0,59.0,40.0
31,113,7.0,7.0,62.0,49.0,61.0,63.0

In [264]:
import pandas as pd

df1 = pd.read_csv("/content/ogrenciler_1.csv")
df2 = pd.read_csv("/content/ogrenciler_2.csv")

In [265]:
df1

   ogrenci_no    isim       bolum  not
0           1  Elifsu  Bilgisayar   85
1           2   Ahmet     Yazilim   72
2           3    Ayse  Bilgisayar   90
3           4  Mehmet     Yazilim   68
4           5    Elif  Bilgisayar  78s

In [266]:
df2

   ogrenci_no    isim       bolum  not
0           6  Gurkan  Bilgisayar   81
1           7   Leyla     Yazilim   95
2           8  Melike  Bilgisayar   74
3           9   Hasan     Yazilim   88
4          10  Zeynep  Bilgisayar   92

In [267]:
birlesik_df = pd.concat([df1, df2])

In [268]:
birlesik_df

   ogrenci_no    isim       bolum  not
0           1  Elifsu  Bilgisayar   85
1           2   Ahmet     Yazilim   72
2           3    Ayse  Bilgisayar   90
3           4  Mehmet     Yazilim   68
4           5    Elif  Bilgisayar  78s
0           6  Gurkan  Bilgisayar   81
1           7   Leyla     Yazilim   95
2           8  Melike  Bilgisayar   74
3           9   Hasan     Yazilim   88
4          10  Zeynep  Bilgisayar   92

In [269]:
birlesik_df = pd.concat([df1, df2], ignore_index=True)

In [270]:
pd.concat([df1, df2])

   ogrenci_no    isim       bolum  not
0           1  Elifsu  Bilgisayar   85
1           2   Ahmet     Yazilim   72
2           3    Ayse  Bilgisayar   90
3           4  Mehmet     Yazilim   68
4           5    Elif  Bilgisayar  78s
0           6  Gurkan  Bilgisayar   81
1           7   Leyla     Yazilim   95
2           8  Melike  Bilgisayar   74
3           9   Hasan     Yazilim   88
4          10  Zeynep  Bilgisayar   92

In [274]:
birlesik_df = pd.concat([df1, df2], ignore_index=True)

In [275]:
birlesik_df = pd.merge(
    df1,
    df2,
    on="ogrenci_no",
    how="inner"
)